<?php
return [
    'clear' => [
        'url' => 'clear',
        'method' => 'get',
        'action' => 'GeneralController@Clear',
        'secure' => false,
        'localized' => true,
        'unlocalized_url' => null,
    ],
    'get-non-existent-photos' => [
        'url' => 'get-non-existent-photos',
        'method' => 'get',
        'action' => 'GeneralController@GetNonExistentPhotos',
        'secure' => false,
        'localized' => false,
        'unlocalized_url' => 'get-non-existent-photos',
    ],
    'test' => [
        'url' => 'test',
        'method' => 'get',
        'action' => 'GeneralController@Test',
        'secure' => false,
        'localized' => true,
        'unlocalized_url' => null,
    ],
    /******************************************************************************************************************/
    'facebook-request-customer' => [
        'url' => 'facebook-request-customer',
        'method' => 'get',
        'action' => 'FacebookController@RequestCustomer',
        'secure' => false,
        'localized' => false,
        'unlocalized_url' => 'facebook-request-customer',
    ],
    'facebook-request-ecommerce' => [
        'url' => 'facebook-request-ecommerce',
        'method' => 'get',
        'action' => 'FacebookController@RequestMarketplace',
        'secure' => false,
        'localized' => false,
        'unlocalized_url' => 'facebook-request-ecommerce',
    ],
    'facebook-response-customer' => [
        'url' => 'facebook-response-customer',
        'method' => 'get',
        'action' => 'FacebookController@ResponseCustomer',
        'secure' => false,
        'localized' => false,
        'unlocalized_url' => config('env.facebook_response_customer'),
    ],
    'facebook-response-ecommerce' => [
        'url' => 'facebook-response-ecommerce',
        'method' => 'get',
        'action' => 'FacebookController@ResponseMarketplace',
        'secure' => false,
        'localized' => false,
        'unlocalized_url' => config('env.facebook_response_ecommerce'),
    ],
    /******************************************************************************************************************/
    'customer-landing' => [
        'url' => 'customer-landing',
        'method' => 'get',
        'action' => 'CustomerController@Landing',
        'secure' => false,
        'localized' => true,
        'unlocalized_url' => null,
    ],
    'customer-register' => [
        'url' => 'customer-register',
        'method' => 'get',
        'action' => 'CustomerController@Register',
        'secure' => false,
        'localized' => true,
        'unlocalized_url' => null,
    ],
    'customer-send-wellcome-mail' => [
        'url' => 'customer-send-wellcome-mail',
        'method' => 'post',
        'action' => 'CustomerController@SendWellcomeCustomerMail',
        'secure' => false,
        'localized' => false,
        'unlocalized_url' => 'customer-send-wellcome-mail',
    ],
    'customer-send-contact-mail' => [
        'url' => 'customer-send-contact-mail',
        'method' => 'post',
        'action' => 'CustomerController@SendContactMail',
        'secure' => false,
        'localized' => false,
        'unlocalized_url' => 'customer-send-contact-mail',
    ],
    'customer-send-suscriber-mail' => [
        'url' => 'customer-send-suscriber-mail',
        'method' => 'post',
        'action' => 'CustomerController@SendSuscriberMail',
        'secure' => false,
        'localized' => false,
        'unlocalized_url' => 'customer-send-suscriber-mail',
    ],
    'customer-auth-ecommerce' => [
        'url' => 'customer-auth-ecommerce',
        'method' => 'post',
        'action' => 'CustomerController@AuthMarketplace',
        'secure' => false,
        'localized' => false,
        'unlocalized_url' => 'customer-auth-ecommerce',
    ],
    /******************************************************************************************************************/
    'home' => [
        'url' => 'home',
        'method' => 'get',
        'action' => 'ECommerceController@Home',
        'secure' => false,
        'localized' => true,
        'unlocalized_url' => null,
    ],
    'landing' => [
        'url' => 'landing',
        'method' => 'get',
        'action' => 'ECommerceController@Landing',
        'secure' => false,
        'localized' => true,
        'unlocalized_url' => null,
    ],
    'login' => [
        'url' => 'login',
        'method' => 'get',
        'action' => 'ECommerceController@Login',
        'secure' => false,
        'localized' => true,
        'unlocalized_url' => null,
    ],
    'logout' => [
        'url' => 'logout',
        'method' => 'get',
        'action' => 'ECommerceController@Logout',
        'secure' => false,
        'localized' => true,
        'unlocalized_url' => null,
    ],
    'cart' => [
        'url' => 'cart',
        'method' => 'get',
        'action' => 'ECommerceController@Cart',
        'secure' => false,
        'localized' => true,
        'unlocalized_url' => null,
    ],
    'checkout' => [
        'url' => 'checkout',
        'method' => 'get',
        'action' => 'ECommerceController@Checkout',
        'secure' => false,
        'localized' => true,
        'unlocalized_url' => null,
    ],
    'get-cost-env' => [
        'url' => 'get-cost-env',
        'method' => 'post',
        'action' => 'UbicationController@GetCostEnv',
        'secure' => false,
        'localized' => true,
        'unlocalized_url' => 'ubication/cost-env',
    ],
    'order-success' => [
        'url' => 'order-success',
        'method' => 'get',
        'action' => 'ECommerceController@OrderSuccess',
        'secure' => true,
        'localized' => true,
        'unlocalized_url' => null,
    ],
    'izzipay-response' => [
        'url' => 'izzipay-response',
        'method' => 'post',
        'action' => 'IzziPayController@Response',
        'secure' => false,
        'localized' => false,
        'unlocalized_url' => 'izzipay/response',
    ],
    'order-pending' => [
        'url' => 'order-pending',
        'method' => 'get',
        'action' => 'ECommerceController@OrderPending',
        'secure' => true,
        'localized' => true,
        'unlocalized_url' => null,
    ],
    'order-failed' => [
        'url' => 'order-failed',
        'method' => 'get',
        'action' => 'ECommerceController@OrderFailed',
        'secure' => true,
        'localized' => true,
        'unlocalized_url' => null,
    ],
    'terms' => [
        'url' => 'terms',
        'method' => 'get',
        'action' => 'ECommerceController@TermsAndConditions',
        'secure' => false,
        'localized' => true,
        'unlocalized_url' => null,
    ],
    'politics' => [
        'url' => 'politics',
        'method' => 'get',
        'action' => 'ECommerceController@PoliticsAndPrivacity',
        'secure' => false,
        'localized' => true,
        'unlocalized_url' => null,
    ],
    /******************************************************************************************************************/
    'mercadopago-request' => [
        'url' => 'mercadopago-request',
        'method' => 'post',
        'action' => 'MercadoPagoController@Request',
        'secure' => false,
        'localized' => false,
        'unlocalized_url' => 'mercadopago/request',
    ],
    'mercadopago-response' => [
        'url' => 'mercadopago-response',
        'method' => 'post',
        'action' => 'MercadoPagoController@Response',
        'secure' => false,
        'localized' => false,
        'unlocalized_url' => 'mercadopago/response',
    ],/******************************************************************************************************************/
    'izzipay-request-token' => [
        'url' => 'izzipay-request-token',
        'method' => 'post',
        'action' => 'IzziPayController@getToken',
        'secure' => false,
        'localized' => false,
        'unlocalized_url' => 'izzipay/getToken',
    ],
    'izzipay-request-form' => [
        'url' => 'izzipay-request-form',
        'method' => 'post',
        'action' => 'IzziPayController@GenerateFrom',
        'secure' => false,
        'localized' => false,
        'unlocalized_url' => 'izzipay/getform',
    ],
    /******************************************************************************************************************/
    'catalogue-all' => [
        'url' => 'catalogue-all',
        'method' => 'get',
        'action' => 'CatalogueController@CatalogueAll',
        'secure' => false,
        'localized' => true,
        'unlocalized_url' => null,
    ],
    'catalogue-category' => [
        'url' => 'catalogue-category',
        'method' => 'get',
        'action' => 'CatalogueController@CatalogueCategory',
        'secure' => false,
        'localized' => true,
        'unlocalized_url' => null,
    ],
    'catalogue-cluster' => [
        'url' => 'catalogue-cluster',
        'method' => 'get',
        'action' => 'CatalogueController@CatalogueCluster',
        'secure' => false,
        'localized' => true,
        'unlocalized_url' => null,
    ],
    'catalogue-sale' => [
        'url' => 'catalogue-sale',
        'method' => 'get',
        'action' => 'CatalogueController@CatalogueSale',
        'secure' => false,
        'localized' => true,
        'unlocalized_url' => null,
    ],
    'catalogue-search' => [
        'url' => 'catalogue-search',
        'method' => 'get',
        'action' => 'CatalogueController@CatalogueSearch',
        'secure' => false,
        'localized' => true,
        'unlocalized_url' => null,
    ],
    /******************************************************************************************************************/
    'product' => [
        'url' => 'product',
        'method' => 'get',
        'action' => 'ProductController@ProductDetail',
        'secure' => false,
        'localized' => true,
        'unlocalized_url' => null,
    ],
    'product-preview' => [
        'url' => null,
        'method' => 'post',
        'action' => 'ProductController@GetPreview',
        'secure' => false,
        'localized' => false,
        'unlocalized_url' => 'product/get-preview',
    ],
    'product-catalogue' => [
        'url' => null,
        'method' => 'post',
        'action' => 'ProductController@GetCatalogue',
        'secure' => false,
        'localized' => false,
        'unlocalized_url' => 'product/get-catalogue',
    ],
    /******************************************************************************************************************/
    'cart-add' => [
        'url' => null,
        'method' => 'post',
        'action' => 'CartController@Add',
        'secure' => false,
        'localized' => false,
        'unlocalized_url' => 'cart/add',
    ],
    'cart-qty' => [
        'url' => null,
        'method' => 'post',
        'action' => 'CartController@getQuantity',
        'secure' => false,
        'localized' => false,
        'unlocalized_url' => 'cart/quantity',
    ],
    'cart-price' => [
        'url' => null,
        'method' => 'post',
        'action' => 'CartController@getPrice',
        'secure' => false,
        'localized' => false,
        'unlocalized_url' => 'cart/price',
    ],
    /******************************************************************************************************************/
    'slider-view' => [
        'url' => null,
        'method' => 'post',
        'action' => 'ECommerceController@ViewSlider',
        'secure' => false,
        'localized' => false,
        'unlocalized_url' => 'slider/view',
    ],
    /******************************************************************************************************************/
    'info-politics-hour' => [
        'url' => 'info-politics-hour',
        'method' => 'get',
        'action' => 'ECommerceController@InfoPoliticsOurHor',
        'secure' => false,
        'localized' => true,
        'unlocalized_url' => null,
    ],
    'info-politics-terms' => [
        'url' => 'info-politics-terms',
        'method' => 'get',
        'action' => 'ECommerceController@InfoPoliticsTermCond',
        'secure' => false,
        'localized' => true,
        'unlocalized_url' => null,
    ],
    'info-politics-env' => [
        'url' => 'info-politics-env',
        'method' => 'get',
        'action' => 'ECommerceController@InfoPoliticsCostEnv',
        'secure' => false,
        'localized' => true,
        'unlocalized_url' => null,
    ],
    'info-politics-privacity' => [
        'url' => 'info-politics-privacity',
        'method' => 'get',
        'action' => 'ECommerceController@InfoPoliticsPrivacity',
        'secure' => false,
        'localized' => true,
        'unlocalized_url' => null,
    ],
    'info-politics-cookies' => [
        'url' => 'info-politics-cookies',
        'method' => 'get',
        'action' => 'ECommerceController@InfoPoliticsCookies',
        'secure' => false,
        'localized' => true,
        'unlocalized_url' => null,
    ],
    'info-politics-tratament' => [
        'url' => 'info-politics-tratament',
        'method' => 'get',
        'action' => 'ECommerceController@InfoPoliticsTratament',
        'secure' => false,
        'localized' => true,
        'unlocalized_url' => null,
    ],
    'info-politics-shops' => [
        'url' => 'info-politics-shops',
        'method' => 'get',
        'action' => 'ECommerceController@InfoPoliticsOurShops',
        'secure' => false,
        'localized' => true,
        'unlocalized_url' => null,
    ],
    'info-politics-history' => [
        'url' => 'info-politics-history',
        'method' => 'get',
        'action' => 'ECommerceController@InfoPoliticsOurHistory',
        'secure' => false,
        'localized' => true,
        'unlocalized_url' => null,
    ],
];
